### ISSUE TITLE
Push the 0.1.1 release?

### ISSUE THREAD

**Issue by halostatue** [xtian/credo_contrib#7]
`credo_contrib` 0.1 is not compatible with `credo` 1.0 without an explicit override, but the `master` branch of `credo_contrib` specifies compatibility. Pushing the new version would allow this to continue o work (although I would recommend that the version be bumped to `0.2` instead of `0.1.1` for better clarity re: semantic versioning).

**Comment by xtian** [comment]
Published: https://hex.pm/packages/credo_contrib/0.1.1

I decided it would be better to communicate that our API is unchanged so I left it at `0.1.1`
